name: "template-repo-sync-action"
description: "Action for taking the files in a template repo and synchronizing them to the repo via a PR"
branding:
  icon: git-merge
  color: blue
inputs:
  repoPath:
    description: "The owner/repo path of the repo on github"
    required: true
  githubToken:
    description: "The github token with access to write pull requests on this repo"
    required: true
  remoteRepoToken:
    description: A separate github token with permissions to clone from the other repo.  Only needed for private repos
    required: false
  repoRoot:
    description: "The root in this github repo that we are syncing.  This is mainly for things like monorepos."
    required: false
  templateBranch:
    description: "The branch on the template that we want to sync to"
    required: true
  branchPrefix:
    description: "A short branch prefix for the branch that will be created in order to store the changes"
    required: false
  commitMsg:
    description: "The commit message to supply when making the merge commits"
    required: false
  titleMsg:
    description: "The title of the pull request"
    required: false
  prToBranch:
    description: This is the branch to open the pull request to.  If not set, this uses the repo's default branch.
    required: false
  updateAfterRef:
    description: Whether we want to override the templatesync.local.json file with the template repo's last sha from the sync
    required: false
    default: "true"
  mockLocalConfig:
    description: For testing, this is a templatesync.config.json that overrides the file that might be on the branch
    required: false
outputs:
  prNumber:
    description: "The number of the created PR"
runs:
  using: "node20"
  main: "bundle/index.js"
