name: PR Checks
run-name: ${{ github.head_ref }} PR Checks

on:
  pull_request:
    branches: [ main, alpha ]

jobs:
  call-test-workflow:
    uses: ./.github/workflows/test-flow.yaml
    with:
      from: ${{ github.workflow }}